name: Trigger remote workflow
on: push
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: |
        curl
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.REMOTE_ACTION_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/DedlySpyder/ActionsSandbox/actions/workflows/manual_workflow.yaml/dispatches
          -d '{"ref":"master","inputs":{"experimental":"1.0.0","stable":"1.0.1"}}'
